<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net80-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BallisticCalculator" Version="1.1.11" />
    <PackageReference Include="Gehtsoft.Measurements" Version="1.1.17" />
  </ItemGroup>
</Project>